DROP DATABASE IF EXISTS URBAN_EYE;
CREATE DATABASE URBAN_EYE; -- to stores characters with sinhala and tamil (CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;)
USE URBAN_EYE;

CREATE TABLE COUNCIL(
    COUNCIL_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    COUNCIL_NAME VARCHAR(100) NOT NULL UNIQUE,
    COUNCIL_TYPE ENUM('Municipal Council') NOT NULL,
    DISTRICT VARCHAR(60) NOT NULL,
    PROVINCE VARCHAR(60) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP -- TIMESTAMP date and time (data type), DEFAULT CURRENT_TIMESTAMP if don't fill it, it fill default with current date and time

)ENGINE=InnoDB; -- IN THIS ENGINE STORES THIS TABLE

CREATE TABLE WARD( 
    WARD_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, -- unsigned for not negative numbers
    COUNCIL_ID INT UNSIGNED NOT NULL UNIQUE, -- UNIQE KEY is used for forbids duplicates
    WARD_NAME VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(255) NULL,
    CONSTRAINT WARD_COUNCIL FOREIGN KEY (COUNCIL_ID) REFERENCES COUNCIL (COUNCIL_ID) 
    ON UPDATE CASCADE -- KEEP THE CHILD ROWS IN SYNC WHEN PARENT ID CHANGES
    ON DELETE RESTRICT -- PROTECT PARENT ROWS FROM DELETION WHILE CHILDREN EXISTS
    
)ENGINE= InnODB;

CREATE TABLE CITIZEN(
    CITIZEN_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    WARD_ID  INT UNSIGNED NOT NULL,
    NIC_HASH CHAR(64) NOT NULL UNIQUE, -- CHAR IS USED FOR FIXED LENGTH CODES
    FULL_NAME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(150) NULL UNIQUE,
    MOBILE_NUMBER VARCHAR(15) NOT NULL,
    ADDRESS VARCHAR(255) NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    CREDIBILITY_SCORE INT NOT NULL DEFAULT 100,
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1, -- TINYINT means 1 byte of integer type storage
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT CITIZEN_WARD FOREIGN KEY (WARD_ID) REFERENCES WARD(WARD_ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT

)ENGINE= InnoDB;

CREATE TABLE OFFICER(
    OFFICER_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    COUNCIL_ID INT UNSIGNED NOT NULL,
    WARD_ID INT UNSIGNED NOT NULL,
    EMPLOYEE_ID VARCHAR(50) NOT NULL UNIQUE,
    FULL_NAME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    DEPARTMENT VARCHAR(100) NULL,
    ROLE ENUM('Field Officer', 'Supervisor', 'Admin') NOT NULL DEFAULT 'Field Officer',
    IS_ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT OFFICER_COUNCIL FOREIGN KEY (COUNCIL_ID) REFERENCES COUNCIL (COUNCIL_ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
    CONSTRAINT OFFICER_WARD FOREIGN KEY (WARD_ID) REFERENCES WARD (WARD_ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT -- IF THE PARENT ROW DELETED SET THE CHILD'S FOREIGN KEY COLUMN TO NULL WITHOUT DELETE IT
    
)ENGINE= InnoDB;

CREATE TABLE ISSUE(
    ISSUE_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CITIZEN_ID INT UNSIGNED NOT NULL,
    WARD_ID INT UNSIGNED NOT NULL,
    OFFICER_ID INT UNSIGNED NOT NULL,
    TITLE VARCHAR(150) NOT NULL,
    DESCRIPTION TEXT NOT NULL, -- It is a data type that stores large amounts of text
    CATEGORY ENUM('Road Hazard', 'Water Drainage','Waste Management', 'Street Lighting', 'Other') NOT NULL,
    STATUS ENUM ('Open', 'In Progress', 'Resolved','Closed','Disputed') NOT NULL DEFAULT 'Open',
    IS_EMERGENCY TINYINT(1) NOT NULL DEFAULT 0,
    PRIORITY_SCORE INT NOT NULL DEFAULT 0,
    BEFORE_PHOTO VARCHAR(500) NULL, -- This will be firebase storage link
    CLOSURE_TYPE ENUM('Reporter Confirmed', 'Auto Closed') NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    RESOLVED_AT DATETIME NULL,
    CLOSED_AT DATETIME NULL,
    CONSTRAINT ISSUE_CITIZEN FOREIGN KEY (CITIZEN_ID) REFERENCES CITIZEN (CITIZEN_ID) 
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
    CONSTRAINT ISSUE_WARD FOREIGN KEY (WARD_ID) REFERENCES WARD (WARD_ID) 
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
    CONSTRAINT ISSUE_OFFICER FOREIGN KEY (OFFICER_ID) REFERENCES OFFICER(OFFICER_ID) 
    ON UPDATE CASCADE
    ON DELETE RESTRICT

)ENGINE= InnoDB;